Sync master with `release/v1.0.6`
mt-support/tribe-ext-test-data-generator pull request #20
Opened 2022-05-20 14:06 UTC by juanfra

Syncing changes merged to master into `release/v1.0.6`

2022-05-24 14:44 UTC, ghost commented
@bordoni can you take a look at this? I'm not sure what the conflicts are.

2022-06-20 15:46 UTC, Camwyn commented on src/Tribe/Page.php
> +		if ( class_exists( 'Tribe__Events__Main' ) ) {
This conditional isn't needed - the plugin won't run w/o TEC:
https://github.com/mt-support/tribe-ext-test-data-generator/blob/main/src/Tribe/Plugin_Register.php#L29

2022-06-20 15:48 UTC, Camwyn commented on src/Tribe/Page.php
> +			$parent = \Tribe\Tickets\Admin\Settings::$parent_slug;
Do we want the plugin to run when ET standalone is active? 
w/o TEC we don't have Events, Venues, or Organizers.
All we get is dummy images and clearing Events data/resetting settings 🤔

2022-06-20 15:49 UTC, Camwyn commented on src/Tribe/Page.php
> +			$parent = \Tribe\Tickets\Admin\Settings::$parent_slug;
If we do - we need to change the plugin dependencies 😉

2022-06-20 15:50 UTC, Camwyn requested changes
Decide if we want this to run with ET standalone and correct the dependencies if we do.

2022-06-20 15:55 UTC, tecjoel commented on src/Tribe/Page.php
> +			$parent = \Tribe\Tickets\Admin\Settings::$parent_slug;
@Camwyn for now this won't run with standalone ET, since it runs on events and all ET-related things only happen for events.

2022-06-20 16:03 UTC, ghost commented
@Camwyn for now this won't run with standalone ET, since it runs on events and all ET-related things only happen for events.

In another hand, what happened is that the changes with required fixes to make this work after the standalone Tickets Menu work was merged directly into main instead of a separate branch, so now main is ahead of this. Need to get main merged into this branch and then do whatever other updates as required and prep a v1.0.7 release.

2022-06-24 13:17 UTC, merged